#!/bin/env python3
import sqlite3
import json
print('Content-type: text\n\n')
conn = sqlite3.connect('database.db')
cursor = conn.cursor()
cursor.execute("select * from powerstatus order by sitename")
junk=cursor.fetchall()
myjson={}
for item in junk:
  if item[0] not in myjson:
    myjson[item[0]]={"checks":[]}
  for idx,porzingas in enumerate(item):
    if porzingas=='none' or idx<2:
      continue
    myjson[item[0]]['checks'].append(porzingas)
print(json.dumps(myjson))
